name: dotnet-releaser

on:
  push:
    tags:
    - '*'
    paths-ignore:
    - 'CHANGELOG.md'
    - 'LICENSE.txt'
    - 'README.md'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install .NET 10.0
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '10.0.x'

    - name: Build and Publish
      if: github.event_name == 'push'
      shell: bash
      run: |
        mkdir "../Libraries/"
        git clone "https://github.com/bluetuith-org/MyPhone.Obex" "../Libraries/MyPhone.OBEX"
        dotnet tool install --global dotnet-releaser
        dotnet tool install --global csharpier
        dotnet-releaser run --github-token "${{secrets.GITHUB_TOKEN}}" "src/dotnet-releaser.toml"
